---
- name: testuojam paslaptis
  hosts: local
  connection: local
  vars:
    vault_file: secrets.yml
  tasks:
    - name: Include vault secrets
      include_vars:
        file: "{{ vault_file }}"
        name: secrets
    - name: show secret values
      debug:
        msg: "secret key: {{ secrets.secret_key }}, API pass: {{ secrets.api_password }}"
