version = 0.1
[default.deploy.parameters]
stack_name = "cars-api-sam"
resolve_s3 = true
s3_prefix = "cars-api-sam"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
