services:

  #Flask
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  # Redis duombazė
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # Workerio servisas
  worker:
    build: ./worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
