name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check Docker Username
      run: echo "Docker Username: "${{ env.DOCKER_USER }}"   
    - name: Login to Docker
      run: docker login -u {{ karabasas }} -p $secret.DOCKER_PASS
    - name: Build Docker image
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "karabasas" --password-stdin
    - name: Push Image
      run: docker push karabasas/test:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME_INFI }}
        password: ${{ secrets.DOCKERHUB_TOKEN_INFI }}