name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  

    - name: Login to Docker
      run: docker login -u karabasas -p ${{ secrets.DOCKER_PASS }}
    - name: Build Docker image
      run: docker build -t karabasas/test:latest . --file Dockerfile
    - name: Push Image
      run: docker push karabasas/test:latest

