name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  

    - name: Login to Docker
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "karabasas" --password-stdin
    - name: Build Docker image
      run: docker build -t karabasas/test:latest . --Dockerfile
    - name: Push Image
      run: docker push karabasas/test:latest

