name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker
      run: docker login -u ${{ env.DOCKER_USER }} -p ${{ secret.DOKCER_PASS }}
    - name: Build Docker image
      run: docker build . --file Dockerfile karabasas/test:latest
    - name: Push Image
      run: docker push karabasas/test:latest