name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request: 
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        if: contains(github.event.head_commit.message, 'paiton')
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Set up python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8
            - name: Run linter
              run: |
                flake8 .
    
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.8'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install unittest 
            - name: Run tests
              run: |
                python -m unittest discover tests
    
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.8'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install unittest
            - name: Build Package
              run: |
                echo "Build proccess complete"
    
    push:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Push App
          run: |
            echo "App pushed successfuly"

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy app
              run: docker push karabasas ci_cd:latest
